import '../models/achievement.dart';

const List<Achievement> allAchievements = [
  Achievement(
    id: 'first_flame',
    name: 'First Flame',
    description: 'Complete your very first habit. Every journey begins with a single step!',
    icon: '\u{1F525}',
    requirement: 'Complete your first habit',
    category: AchievementCategory.completion,
    xpReward: 25,
  ),
  Achievement(
    id: 'week_warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak on any habit. A full week of consistency!',
    icon: '\u{2694}\u{FE0F}',
    requirement: '7-day streak on any habit',
    category: AchievementCategory.streak,
    xpReward: 50,
  ),
  Achievement(
    id: 'fortnight_force',
    name: 'Fortnight Force',
    description: 'Push through to a 14-day streak. Two weeks of dedication!',
    icon: '\u{1F4AA}',
    requirement: '14-day streak on any habit',
    category: AchievementCategory.streak,
    xpReward: 100,
  ),
  Achievement(
    id: 'monthly_master',
    name: 'Monthly Master',
    description: 'Achieve a 30-day streak. A full month of unwavering commitment!',
    icon: '\u{1F451}',
    requirement: '30-day streak on any habit',
    category: AchievementCategory.streak,
    xpReward: 200,
  ),
  Achievement(
    id: 'century_club',
    name: 'Century Club',
    description: 'Reach 100 total habit completions across all your habits.',
    icon: '\u{1F4AF}',
    requirement: '100 total completions',
    category: AchievementCategory.completion,
    xpReward: 150,
  ),
  Achievement(
    id: 'perfect_day',
    name: 'Perfect Day',
    description: 'Complete every single active habit in one day. A perfect score!',
    icon: '\u{2B50}',
    requirement: 'Complete all habits in one day',
    category: AchievementCategory.completion,
    xpReward: 75,
  ),
  Achievement(
    id: 'early_bird',
    name: 'Early Bird',
    description: 'Complete all morning habits before 8 AM for 7 consecutive days.',
    icon: '\u{1F426}',
    requirement: 'Complete all morning habits before 8 AM for 7 days',
    category: AchievementCategory.special,
    xpReward: 100,
  ),
  Achievement(
    id: 'night_owl',
    name: 'Night Owl',
    description: 'Maintain all evening habits consistently for 14 days straight.',
    icon: '\u{1F989}',
    requirement: 'Evening habits for 14 days',
    category: AchievementCategory.special,
    xpReward: 100,
  ),
  Achievement(
    id: 'habit_collector',
    name: 'Habit Collector',
    description: 'Track 10 or more active habits simultaneously.',
    icon: '\u{1F4DA}',
    requirement: 'Track 10+ habits',
    category: AchievementCategory.special,
    xpReward: 75,
  ),
  Achievement(
    id: 'consistency_king',
    name: 'Consistency King',
    description: 'Maintain 80%+ completion rate across all habits for 30 days.',
    icon: '\u{1F3AF}',
    requirement: '80%+ completion rate for 30 days',
    category: AchievementCategory.completion,
    xpReward: 200,
  ),
  Achievement(
    id: 'streak_saver',
    name: 'Streak Saver',
    description: 'Use a streak freeze to protect your progress.',
    icon: '\u{2744}\u{FE0F}',
    requirement: 'Use a streak freeze',
    category: AchievementCategory.special,
    xpReward: 25,
  ),
  Achievement(
    id: 'ai_student',
    name: 'AI Student',
    description: 'Read 50 coach tips and insights. Knowledge is power!',
    icon: '\u{1F916}',
    requirement: 'Read 50 coach tips',
    category: AchievementCategory.special,
    xpReward: 100,
  ),
  Achievement(
    id: 'explorer',
    name: 'Explorer',
    description: 'Try a habit from every available category.',
    icon: '\u{1F9ED}',
    requirement: 'Try a habit from every category',
    category: AchievementCategory.special,
    xpReward: 75,
  ),
  Achievement(
    id: 'comeback_kid',
    name: 'Comeback Kid',
    description: 'Break a streak but come back stronger. Resilience matters!',
    icon: '\u{1F4A5}',
    requirement: 'Recover a broken streak',
    category: AchievementCategory.special,
    xpReward: 50,
  ),
  Achievement(
    id: 'five_alive',
    name: 'Five Alive',
    description: 'Have 5 active habits running simultaneously.',
    icon: '\u{1F590}\u{FE0F}',
    requirement: '5 active habits simultaneously',
    category: AchievementCategory.completion,
    xpReward: 50,
  ),
  Achievement(
    id: 'data_nerd',
    name: 'Data Nerd',
    description: 'Export your habit data. You own your data!',
    icon: '\u{1F4CA}',
    requirement: 'Export your data',
    category: AchievementCategory.special,
    xpReward: 25,
  ),
  Achievement(
    id: 'challenger',
    name: 'Challenger',
    description: 'Complete a weekly challenge from the AI coach.',
    icon: '\u{1F3C5}',
    requirement: 'Complete a weekly challenge',
    category: AchievementCategory.special,
    xpReward: 50,
  ),
  Achievement(
    id: 'social_butterfly',
    name: 'Social Butterfly',
    description: 'Share a streak milestone with friends.',
    icon: '\u{1F98B}',
    requirement: 'Share a streak milestone',
    category: AchievementCategory.special,
    xpReward: 25,
  ),
  Achievement(
    id: 'level_10',
    name: 'Level 10',
    description: 'Reach level 10. You\'re becoming a habit master!',
    icon: '\u{1F31F}',
    requirement: 'Reach level 10',
    category: AchievementCategory.completion,
    xpReward: 150,
  ),
  Achievement(
    id: 'level_25',
    name: 'Level 25',
    description: 'Reach level 25. Elite habit builder status!',
    icon: '\u{1F48E}',
    requirement: 'Reach level 25',
    category: AchievementCategory.completion,
    xpReward: 300,
  ),
  Achievement(
    id: 'three_day_streak',
    name: 'Three in a Row',
    description: 'Complete a 3-day streak on any habit.',
    icon: '\u{1F3C3}',
    requirement: '3-day streak on any habit',
    category: AchievementCategory.streak,
    xpReward: 25,
  ),
  Achievement(
    id: 'sixty_day_streak',
    name: 'Iron Will',
    description: 'Maintain a 60-day streak. Unbreakable discipline!',
    icon: '\u{1F6E1}\u{FE0F}',
    requirement: '60-day streak on any habit',
    category: AchievementCategory.streak,
    xpReward: 300,
  ),
  Achievement(
    id: 'hundred_day_streak',
    name: 'Centurion',
    description: 'Reach a legendary 100-day streak on any habit.',
    icon: '\u{1F3C6}',
    requirement: '100-day streak on any habit',
    category: AchievementCategory.streak,
    xpReward: 500,
  ),
  Achievement(
    id: 'weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Complete all habits on both Saturday and Sunday for 4 weeks.',
    icon: '\u{1F389}',
    requirement: 'Complete all habits on weekends for 4 weeks',
    category: AchievementCategory.completion,
    xpReward: 100,
  ),
  Achievement(
    id: 'multi_streak',
    name: 'Multi-Streaker',
    description: 'Maintain a 7-day streak on 3 or more habits at the same time.',
    icon: '\u{1F386}',
    requirement: '7-day streak on 3+ habits simultaneously',
    category: AchievementCategory.streak,
    xpReward: 150,
  ),
  Achievement(
    id: 'thousand_completions',
    name: 'Thousand Strong',
    description: 'Reach 1,000 total habit completions. Truly dedicated!',
    icon: '\u{1F3C6}',
    requirement: '1,000 total completions',
    category: AchievementCategory.completion,
    xpReward: 500,
  ),
];
